# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20180902_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=b'static/images/'),
        ),
    ]
